// =============================================================================
// Genuine JavaScript model tests + R<->JS equivalence check.
// Run:  node tests/js/model.test.mjs   (or `npm test`)
//
// Strategy: tests/regression/baseline_release.json holds the R-derived golden
// reference (regenerated by tests/regression/capture_baseline.R). The R
// regression test (tests/regression/baseline_test.R) asserts R still matches
// that reference; this file asserts the JavaScript in web/index.html matches the
// same reference. Together they enforce R<->JS numerical equivalence in CI:
//   R == golden  AND  JS == golden  =>  R == JS.
// =============================================================================

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { loadModel } from './extract-model.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REF = JSON.parse(fs.readFileSync(
  path.join(HERE, '..', 'regression', 'baseline_release.json'), 'utf8'));

const TOL_REL_ABS = 1e-9;                       // release vs R golden
const TOL_TISSUE_ABS = REF.tissue_tolerance_abs; // tissue vs R golden (0.05)

let pass = 0, fail = 0;
const ok = (cond, msg) => cond ? pass++ : (fail++, console.log('  FAIL:', msg));
const maxAbs = (a, b) => Math.max(...a.map((v, i) => Math.abs(v - b[i])));

const { release, solveTissue } = await loadModel();
const p = REF.parameters;               // {r,h,C0,K,Dr,kf,np,kz,kH,kp,Dt,ro,ke,te}
p.bc = 'sink';

// ---- 1. Release models vs R golden reference --------------------------------
let worstRelease = 0;
for (const m of Object.keys(REF.release)) {
  const js = REF.release_times.map(t => release(m, t, p));
  const d = maxAbs(js, REF.release[m]);
  worstRelease = Math.max(worstRelease, d);
  ok(d < TOL_REL_ABS, `release '${m}' JS vs R golden: max|Δ|=${d.toExponential(2)}`);
}
console.log(`  [info] release models worst |JS-R| = ${worstRelease.toExponential(2)}`);

// ---- 2. Tissue solver vs R golden reference ---------------------------------
const N = 200, tArr = [], surfArr = [];
for (let i = 0; i <= N; i++) { const t = p.te * i / N; tArr.push(t); surfArr.push(p.C0 * release(REF.tissue_driver, t, p)); }
const sol = solveTissue({ ...p, drive: REF.tissue_driver }, surfArr, tArr);
const nearest = xq => { let bi = 0, bd = 1e9; for (let i = 0; i < sol.x.length; i++) { const d = Math.abs(sol.x[i] - xq); if (d < bd) { bd = d; bi = i; } } return sol.Cfinal[bi]; };
const jsTissue = REF.tissue_x.map(nearest);
const dTissue = maxAbs(jsTissue, REF.tissue_C_final);
ok(dTissue < TOL_TISSUE_ABS, `tissue profile JS vs R golden: max|Δ|=${dTissue.toExponential(2)}`);
console.log(`  [info] tissue worst |JS-R| = ${dTissue.toExponential(2)} (surface≈100)`);

// ---- 3. Structural invariants (multiple parameter sets, incl. edge cases) ----
const paramSets = [
  p,
  { ...p, r: 0.02, h: 0.005, Dr: 5e-3, ke: 0 },      // small particle, no clearance
  { ...p, r: 1.0, h: 0.5, Dr: 1e-4, ke: 1.0 },        // large particle, high clearance
  { ...p, te: 6 },                                     // short horizon
  { ...p, te: 120 },                                   // long horizon
];
const models = Object.keys(REF.release);
for (const ps of paramSets) {
  for (const m of models) {
    const times = Array.from({ length: 25 }, (_, i) => ps.te * i / 24);
    const f = times.map(t => release(m, t, ps));
    ok(f.every(v => v >= 0 && v <= 1 && Number.isFinite(v)), `${m}: fraction in [0,1] & finite`);
    ok(f.every((v, i) => i === 0 || v >= f[i - 1] - 1e-12), `${m}: monotonic non-decreasing`);
    ok(Math.abs(f[0]) < 1e-12, `${m}: f(0)=0`);
  }
}

// ---- 4. Edge-case physics: higher clearance -> shallower penetration --------
function penDepth(ps) {
  const tA = [], sA = [];
  for (let i = 0; i <= N; i++) { const t = ps.te * i / N; tA.push(t); sA.push(ps.C0 * release('first_order', t, ps)); }
  const s = solveTissue({ ...ps, drive: 'first_order' }, sA, tA);
  const cutoff = 0.1 * s.Cfinal[0];
  for (let i = 0; i < s.Cfinal.length; i++) if (s.Cfinal[i] < cutoff) return s.x[i] - ps.r;
  return ps.ro - ps.r;
}
ok(penDepth({ ...p, ke: 1.0 }) <= penDepth({ ...p, ke: 0.0 }) + 1e-9,
   'higher clearance -> penetration not deeper');

// ---- 5. Fickian long-time limit -> ~full release ----------------------------
ok(Math.abs(release('fickian_sphere', 1e6, p) - 1) < 1e-3, 'fickian sphere -> 1 at long time');

console.log(`\nJavaScript model tests: ${pass} passed, ${fail} failed`);
process.exit(fail > 0 ? 1 : 0);
