// Phase-2B AUTHORITATIVE MANIFEST CONTRACT.
//
// The manifest is generated by tools/blender/build_phase2_realism.py from the actual Blender scene:
// event timings come from EVT_* timeline markers, statistics from the exported meshes, and the
// clip name/duration from the baked action. Nothing in this file may invent a value — its job is to
// REJECT a manifest that does not describe the asset, not to paper over one.
//
// Validation runs in three places (ss23):
//   * build time   — tools/verify-baked-asset.mjs
//   * test time    — tests/phase2bAsset.test.mjs
//   * browser load — bakedApplicationScene.js, before the mixer is created
//
// Deliberately dependency-free: the repository ships no JSON-Schema runtime, and adding one for a
// single document would be a heavier dependency than the check itself. The .schema.json file beside
// the manifest is the published contract; this module is the executable form of the same rules.

export const SCHEMA_VERSION = 1;

export const PRESENTATION_MODES = Object.freeze(['blender-baked', 'procedural-fallback']);

export const PROVENANCE_VALUES = Object.freeze(['SIMULATION_DERIVED', 'PREDICTED_VISUAL', 'VISUAL_ONLY']);

export const OWNERSHIP_VALUES = Object.freeze({
  bones: ['blender-baked', 'procedural'],
  morphTargets: ['blender-baked', 'procedural'],
  camera: ['threejs'],
  timeline: ['master-progress'],
  surfaceShader: ['threejs-glsl'],
});

/** The storyboard order of ss10. A manifest whose events are out of order is rejected. */
export const EVENT_ORDER = Object.freeze([
  'neutral',
  'productEstablishStart',
  'gripPreparation',
  'productGripEstablished',
  'dispensePreparation',
  'dispenseStart',
  'creamContact',
  'dispenseEnd',
  'productRetreatStart',
  'productRetreatEnd',
  'handApproach',
  'skinContact',
  'spreadStart',
  'strokeOne',
  'strokeTwo',
  'releaseStart',
  'releaseEnd',
  'heroStart',
  'heroHold',
  'sequenceEnd',
]);

export const REQUIRED_OBJECTS = Object.freeze([
  'humanRoot', 'bodyMesh', 'tube', 'cap', 'creamStrand', 'creamDeposit', 'creamSpread',
  // runtime camera anchors baked into the asset, so Three.js tracks the exact points the animation
  // was authored around rather than re-deriving them from copied bone maths
  'nozzleAnchor', 'depositAnchor',
]);

export const REQUIRED_MORPH_SEMANTICS = Object.freeze([
  'tubeSqueeze', 'tubeDepletion', 'skinIndent', 'creamNozzle', 'creamStrand',
  'creamDeposit', 'creamSpread',
]);

const isFiniteNumber = (v) => typeof v === 'number' && Number.isFinite(v);
const isNonEmptyString = (v) => typeof v === 'string' && v.length > 0;

/**
 * Validate a manifest object on its own terms (no GLB required).
 *
 * @param {object} m
 * @returns {{ ok:boolean, errors:string[], warnings:string[] }}
 */
export function validateManifest(m) {
  const errors = [];
  const warnings = [];
  const fail = (msg) => errors.push(msg);

  if (!m || typeof m !== 'object') return { ok: false, errors: ['manifest is not an object'], warnings };

  // ---- version + identity ----
  if (m.schemaVersion !== SCHEMA_VERSION) fail(`schemaVersion ${m.schemaVersion} is not supported (expected ${SCHEMA_VERSION})`);
  if (!isNonEmptyString(m.assetVersion)) fail('assetVersion is missing');
  if (!isNonEmptyString(m.asset)) fail('asset is missing');
  else if (/^([a-z]+:)?\/\//i.test(m.asset) || m.asset.startsWith('/')) fail(`asset path must be local and relative, got "${m.asset}"`);

  // ---- clip ----
  const clip = m.clip;
  if (!clip || typeof clip !== 'object') fail('clip block is missing');
  else {
    if (!isNonEmptyString(clip.name)) fail('clip.name is missing');
    if (!isFiniteNumber(clip.durationSeconds) || clip.durationSeconds <= 0) fail('clip.durationSeconds must be finite and positive');
    if (!isFiniteNumber(clip.fps) || clip.fps <= 0) fail('clip.fps must be finite and positive');
    if (isFiniteNumber(clip.frameStart) && isFiniteNumber(clip.frameEnd)) {
      if (clip.frameEnd <= clip.frameStart) fail('clip.frameEnd must be after clip.frameStart');
      const implied = (clip.frameEnd - clip.frameStart) / clip.fps;
      if (Math.abs(implied - clip.durationSeconds) > 1e-3) {
        fail(`clip.durationSeconds ${clip.durationSeconds} disagrees with the frame range (${implied.toFixed(4)}s)`);
      }
    }
  }

  // ---- source provenance ----
  const src = m.source;
  if (!src || typeof src !== 'object') fail('source block is missing');
  else {
    if (!isNonEmptyString(src.originalAsset)) fail('source.originalAsset is missing');
    if (!/^[0-9a-f]{64}$/i.test(String(src.originalAssetChecksum || ''))) fail('source.originalAssetChecksum is not a sha256 digest');
    if (!isNonEmptyString(src.blenderVersion)) fail('source.blenderVersion is missing');
    if (!isNonEmptyString(src.blenderSource)) fail('source.blenderSource is missing');
  }

  // ---- skeleton ----
  const sk = m.skeleton;
  if (!sk || typeof sk !== 'object') fail('skeleton block is missing');
  else {
    if (!isNonEmptyString(sk.boneMapVersion)) fail('skeleton.boneMapVersion is missing');
    if (!Number.isInteger(sk.boneCount) || sk.boneCount <= 0) fail('skeleton.boneCount must be a positive integer');
    if (sk.compatibilityStatus !== 'verified') fail(`skeleton.compatibilityStatus must be "verified", got "${sk.compatibilityStatus}"`);
  }

  // ---- objects ----
  if (!m.objects || typeof m.objects !== 'object') fail('objects block is missing');
  else {
    for (const key of REQUIRED_OBJECTS) {
      if (!isNonEmptyString(m.objects[key])) fail(`objects.${key} is missing`);
    }
  }

  // ---- morph targets ----
  if (!m.morphTargets || typeof m.morphTargets !== 'object') fail('morphTargets block is missing');
  else {
    for (const key of REQUIRED_MORPH_SEMANTICS) {
      const entry = m.morphTargets[key];
      if (!entry || typeof entry !== 'object') { fail(`morphTargets.${key} is missing`); continue; }
      if (!isNonEmptyString(entry.mesh)) fail(`morphTargets.${key}.mesh is missing`);
      if (!Array.isArray(entry.targets) || entry.targets.length === 0) fail(`morphTargets.${key}.targets is empty`);
      else if (!entry.targets.every(isNonEmptyString)) fail(`morphTargets.${key}.targets contains a non-string`);
    }
  }

  // ---- events: normalized, ordered, anchored at both ends ----
  const ev = m.events;
  if (!ev || typeof ev !== 'object') fail('events block is missing');
  else {
    for (const name of EVENT_ORDER) {
      if (!(name in ev)) { fail(`events.${name} is missing`); continue; }
      const v = ev[name];
      if (!isFiniteNumber(v)) fail(`events.${name} is not a finite number`);
      else if (v < 0 || v > 1) fail(`events.${name} = ${v} is outside 0..1`);
    }
    if (ev.neutral !== 0) fail(`events.neutral must be exactly 0, got ${ev.neutral}`);
    if (ev.sequenceEnd !== 1) fail(`events.sequenceEnd must be exactly 1.0, got ${ev.sequenceEnd}`);
    let prev = -Infinity; let prevName = '(start)';
    for (const name of EVENT_ORDER) {
      const v = ev[name];
      if (!isFiniteNumber(v)) continue;
      if (v < prev) fail(`event ordering violated: ${name}=${v} precedes ${prevName}=${prev}`);
      prev = v; prevName = name;
    }
  }

  // ---- ownership: exactly one system per channel ----
  const own = m.ownership;
  if (!own || typeof own !== 'object') fail('ownership block is missing');
  else {
    for (const [key, allowed] of Object.entries(OWNERSHIP_VALUES)) {
      if (!allowed.includes(own[key])) fail(`ownership.${key} = "${own[key]}" is not one of ${allowed.join(', ')}`);
    }
  }

  // ---- provenance ----
  const prov = m.provenance;
  if (!prov || typeof prov !== 'object') fail('provenance block is missing');
  else {
    for (const [key, value] of Object.entries(prov)) {
      if (!PROVENANCE_VALUES.includes(value)) fail(`provenance.${key} = "${value}" is not a recognised provenance value`);
    }
    for (const key of ['humanMotion', 'productMotion', 'tubeSqueeze', 'creamExtrusion', 'skinIndentation', 'camera']) {
      if (!(key in prov)) fail(`provenance.${key} is missing`);
    }
  }

  // ---- compatibility ----
  const compat = m.compatibility;
  if (!compat || typeof compat !== 'object') fail('compatibility block is missing');
  else {
    if (compat.gltf !== '2.0') fail(`compatibility.gltf must be "2.0", got "${compat.gltf}"`);
    if (!isNonEmptyString(compat.threeRevision)) fail('compatibility.threeRevision is missing');
    if (!Array.isArray(compat.presentationModes) || compat.presentationModes.length !== PRESENTATION_MODES.length
      || !PRESENTATION_MODES.every((mode) => compat.presentationModes.includes(mode))) {
      fail(`compatibility.presentationModes must list exactly ${PRESENTATION_MODES.join(' and ')}`);
    }
  }

  // ---- statistics ----
  const st = m.statistics;
  if (!st || typeof st !== 'object') fail('statistics block is missing');
  else {
    for (const key of ['fileSizeBytes', 'meshCount', 'triangleCount', 'materialCount',
      'textureCount', 'animationTrackCount', 'morphTargetCount']) {
      if (!isFiniteNumber(st[key]) || st[key] < 0) fail(`statistics.${key} must be a non-negative number`);
    }
    if (isFiniteNumber(st.triangleCount) && st.triangleCount > 400_000) {
      warnings.push(`statistics.triangleCount ${st.triangleCount} is above the 400k budget`);
    }
  }

  return { ok: errors.length === 0, errors, warnings };
}

/**
 * Second-stage validation: every name the manifest promises must actually exist in the loaded GLB.
 *
 * @param {object} m manifest
 * @param {{ objectNames:Set<string>|string[], morphDictionaries:Record<string,object>,
 *           clipNames:string[], clipDuration?:number }} actual
 */
export function validateAgainstAsset(m, actual) {
  const errors = [];
  const names = actual.objectNames instanceof Set ? actual.objectNames : new Set(actual.objectNames || []);
  const dicts = actual.morphDictionaries || {};

  for (const key of REQUIRED_OBJECTS) {
    const name = m.objects && m.objects[key];
    if (name && !names.has(name)) errors.push(`objects.${key} = "${name}" is not present in the loaded asset`);
  }

  const clips = actual.clipNames || [];
  if (m.clip && !clips.includes(m.clip.name)) {
    errors.push(`clip "${m.clip && m.clip.name}" is not in the asset (found: ${clips.join(', ') || 'none'})`);
  }
  if (m.clip && isFiniteNumber(actual.clipDuration)
    && Math.abs(actual.clipDuration - m.clip.durationSeconds) > 0.05) {
    errors.push(`clip duration ${actual.clipDuration.toFixed(3)}s disagrees with the manifest's ${m.clip.durationSeconds}s`);
  }

  for (const key of REQUIRED_MORPH_SEMANTICS) {
    const entry = m.morphTargets && m.morphTargets[key];
    if (!entry) continue;
    // A Blender object with several materials exports as one glTF mesh with several primitives,
    // which three.js loads as a Group whose CHILDREN carry the morph dictionaries. Look through the
    // named node's subtree, not just the node itself.
    const dict = dicts[entry.mesh];
    if (!dict) { errors.push(`morphTargets.${key}: mesh "${entry.mesh}" has no morph targets in the asset`); continue; }
    for (const target of entry.targets) {
      if (!(target in dict)) errors.push(`morphTargets.${key}: "${target}" is missing from mesh "${entry.mesh}"`);
    }
  }
  return { ok: errors.length === 0, errors };
}

/**
 * Fetch and validate in one step. Rejects rather than returning a partially-filled manifest —
 * ss23 forbids silently defaulting a missing required field.
 */
export async function loadManifest(url, fetchImpl = (typeof fetch === 'function' ? fetch : null)) {
  if (!fetchImpl) throw new Error('loadManifest: no fetch implementation available');
  const res = await fetchImpl(url);
  if (!res.ok) throw new Error(`manifest ${url}: HTTP ${res.status}`);
  const json = await res.json();
  const result = validateManifest(json);
  if (!result.ok) throw new Error(`manifest ${url} is invalid:\n  - ${result.errors.join('\n  - ')}`);
  return { manifest: json, warnings: result.warnings };
}

/** Progress -> the storyboard event that is currently active. */
export function eventAt(manifest, progress) {
  const ev = manifest.events;
  let current = EVENT_ORDER[0];
  for (const name of EVENT_ORDER) {
    if (progress + 1e-9 >= ev[name]) current = name;
  }
  return current;
}

/** Normalised 0..1 position between two named events (clamped). */
export function betweenEvents(manifest, from, to, progress) {
  const a = manifest.events[from];
  const b = manifest.events[to];
  if (!isFiniteNumber(a) || !isFiniteNumber(b) || b <= a) return progress >= b ? 1 : 0;
  return Math.max(0, Math.min(1, (progress - a) / (b - a)));
}
